"""empty message

Revision ID: 13d6520c8bef
Revises: 38f3aba6283b
Create Date: 2026-03-03 21:01:20.764677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d6520c8bef'
down_revision = '38f3aba6283b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('affiliate_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliate_number', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
